version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: lmsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: user
      DB_PASSWORD: password
    command: ["start-dev"]
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  lms-backend:
    build: .
    image: ${{ secrets.DOCKER_HUB_USERNAME }}/bitlab-lms:latest
    depends_on:
      - postgres
      - keycloak
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lmsdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/bitlab-academy
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
    ports:
      - "8081:8081"

volumes:
  postgres_data:
  minio_data:
