spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/lmsdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bitlab-academy

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: lms-files

server:
  port: 8081

logging:
  level:
    root: INFO
    com.bitlab: DEBUG
